name: Create release (master branch only)

on:
  push:
    branches:
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        
    - name: Create directories for Debian package structure
      run: |
        mkdir -p fsort_1.0.0
        mkdir -p fsort_1.0.0/usr/local/bin

    - name: Copy necessary files for package
      run: |
        cp -r src/* fsort_1.0.0/usr/local/bin
        cp install.sh fsort_1.0.0
        cp version fsort_1.0.0

    - name: Build .deb package
      run: |
        dpkg-deb --build "fsort_1.0.0"
      
    - name: Create tarball
      run: |
        tar -czvf "fsort-1.0.0.tar.gz" src/ install.sh version

    - name: List generated files
      run: |
        ls -lh

    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      with:
        files: fsort-1.0.0.tar.gz, fsort_1.0.0.deb

    - name: Post-release cleanup
      run: |
        rm -rf fsort_1.0.0
        rm fsort-1.0.0.tar.gz
        rm fsort_1.0.0.deb
